### ISSUE TITLE
Migrate Fleury's Algorithm from iuliagroza/Graph-Algorithms in C++

### ISSUE THREAD

**Issue by iuliagroza** [iuliagroza/Algorithms#13]
Fleury's Algorithm was implemented in C++ [here](https://github.com/iuliagroza/Graph-Algorithms/blob/master/Fleury.cpp).

This algorithm would be a nice addition to our list of algorithms. 

Required implementations:
* pseudocode
* C++14
* Python 3
* Java

This issue focuses on the **C++ implementation**. The same implementation from iuliagroza/Graph-Algorithms can be copied.

**Comment by abhi-jeet-kumar** [comment]
Hey @iuliagroza I am interested in this. can you please assign this issue to me? Thanks

**Comment by iuliagroza** [comment]
> Hey @iuliagroza I am interested in this. can you please assign this issue to me? Thanks

Done. Thank you for your contribution!

**Comment by iuliagroza** [comment]
> Hey @iuliagroza I am interested in this. can you please assign this issue to me? Thanks

Done. Thank you for your contribution!

**Comment by iuliagroza** [comment]
> Hey @iuliagroza before I start, I see multiple issues with different titles but the same comment. Can you please clarify for which issue which language you want please?
> 
> Also, is there a specific way you want PR to be raised?
> 
> Generally. I fork the repo, create a feature branch, raise PR from my fork's branch to origin repo's main branch. Is that okay?

Hi @abhi-jeet-kumar! Thanks for asking!

Each issue focuses on the implementation in a specific language of each algorithm (mentioned both in the title and the description of the issue), so that people with different expertise can contribute to each implementation.

Regarding the general workflow, the README.md of this repository contains a quick [contribution guide](https://github.com/iuliagroza/Algorithms?tab=readme-ov-file#contribution-guide) that you can follow. What's most important is that the style guide and documentation is consistent across all implementations from this repo, so you can follow the structure of other implementations.
