### ISSUE TITLE
Migrate Fleury's Algorithm from iuliagroza/Graph-Algorithms in pseudocode

### ISSUE THREAD

**Issue by iuliagroza** [iuliagroza/Algorithms#16]
Fleury's Algorithm was implemented in C++ [here](https://github.com/iuliagroza/Graph-Algorithms/blob/master/Fleury.cpp).

This algorithm would be a nice addition to our list of algorithms. 

Required implementations:
* pseudocode
* C++14
* Python 3
* Java

This issue focuses on the **pseudocode implementation**.

**Comment by abhi-jeet-kumar** [comment]
Hey @iuliagroza I am interested in this. can you please assign this issue to me? Thanks

**Comment by abhi-jeet-kumar** [comment]
Hey @iuliagroza check [PR](https://github.com/iuliagroza/Algorithms/pull/23)

**Comment by iuliagroza** [comment]
> Hey @iuliagroza check [PR](https://github.com/iuliagroza/Algorithms/pull/23)
> 
> I am holding onto creating more PRs till this one is merged so that I can consolidate all the suggestions/reviews from your end in future PRs to smoothen the review and merging process.

LGTM! Kudos for respecting the guideline and for your great contribution!
