### ISSUE TITLE
Migrate Kempe's Algorithm (Chromatic Number) from iuliagroza/Graph-Algorithms in Python 3

### ISSUE THREAD

**Issue by iuliagroza** [iuliagroza/Algorithms#47]
Kempe's Algorithm (Chromatic Number) was implemented in C++ [here](https://github.com/iuliagroza/Graph-Algorithms/blob/master/KempeChromaticNumber.cpp).

This algorithm would be a nice addition to our list of algorithms. 

Required implementations:
* pseudocode
* C++14
* Python 3
* Java

This issue focuses on the **Python 3 implementation**.

**Comment by Riyazul555** [comment]
Hey @iuliagroza I am closing this issue since all the required changes are fixed
