### ISSUE TITLE
Migrate Kempe's Algorithm (Chromatic Number) from iuliagroza/Graph-Algorithms in Java

### ISSUE THREAD

**Issue by iuliagroza** [iuliagroza/Algorithms#48]
Kempe's Algorithm (Chromatic Number) was implemented in C++ [here](https://github.com/iuliagroza/Graph-Algorithms/blob/master/KempeChromaticNumber.cpp).

This algorithm would be a nice addition to our list of algorithms. 

Required implementations:
* pseudocode
* C++14
* Python 3
* Java

This issue focuses on the **Java implementation**.

**Comment by Riyazul555** [comment]
Hey @iuliagroza please close this issue as I have merged the PR......
Moving ahead over other issues
Thanks.

**Comment by iuliagroza** [comment]
Hey @Riyazul555!

Maybe we can fix the time and space complexities in here as well so it aligns with what we previously discussed in #51 and #52?
